#pragma once
#import "com4j.tlb" no_namespace

template <class T>
class CProxy_ITestObjectEvents : public IConnectionPointImpl<T, &__uuidof( _ITestObjectEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
