/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com4j_SafeArray */

#ifndef _Included_com4j_SafeArray
#define _Included_com4j_SafeArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com4j_SafeArray
 * Method:    releaseArray
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com4j_SafeArray_releaseArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com4j_SafeArray
 * Method:    create0
 * Signature: (I[I)J
 */
JNIEXPORT jlong JNICALL Java_com4j_SafeArray_create0
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     com4j_SafeArray
 * Method:    createAndInit0
 * Signature: (ILjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com4j_SafeArray_createAndInit0
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com4j_SafeArray
 * Method:    getBounds0
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com4j_SafeArray_getBounds0
  (JNIEnv *, jobject);

/*
 * Class:     com4j_SafeArray
 * Method:    getVarType0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com4j_SafeArray_getVarType0
  (JNIEnv *, jobject);

/*
 * Class:     com4j_SafeArray
 * Method:    get0
 * Signature: ([I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com4j_SafeArray_get0
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com4j_SafeArray
 * Method:    set0
 * Signature: (Ljava/lang/Object;[I)V
 */
JNIEXPORT void JNICALL Java_com4j_SafeArray_set0
  (JNIEnv *, jobject, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
