/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com4j_Variant */

#ifndef _Included_com4j_Variant
#define _Included_com4j_Variant
#ifdef __cplusplus
extern "C" {
#endif
#undef com4j_Variant_serialVersionUID
#define com4j_Variant_serialVersionUID -8742448824652078965i64
/*
 * Class:     com4j_Variant
 * Method:    clear0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com4j_Variant_clear0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com4j_Variant
 * Method:    changeType0
 * Signature: (I[J)V
 */
JNIEXPORT void JNICALL Java_com4j_Variant_changeType0
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     com4j_Variant
 * Method:    castToFloat0
 * Signature: ([J)F
 */
JNIEXPORT jfloat JNICALL Java_com4j_Variant_castToFloat0
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com4j_Variant
 * Method:    castToDouble0
 * Signature: ([J)D
 */
JNIEXPORT jdouble JNICALL Java_com4j_Variant_castToDouble0
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com4j_Variant_Type */

#ifndef _Included_com4j_Variant_Type
#define _Included_com4j_Variant_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
