/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com4j_Variant */

#ifndef _Included_com4j_Variant
#define _Included_com4j_Variant
#ifdef __cplusplus
extern "C" {
#endif
#undef com4j_Variant_serialVersionUID
#define com4j_Variant_serialVersionUID -8742448824652078965i64
#undef com4j_Variant_ARRAY
#define com4j_Variant_ARRAY 8192L
#undef com4j_Variant_MISSING_ERROR_CODE
#define com4j_Variant_MISSING_ERROR_CODE -2147352572L
#undef com4j_Variant_MSPD
#define com4j_Variant_MSPD 86400000i64
/*
 * Class:     com4j_Variant
 * Method:    clear0
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com4j_Variant_clear0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com4j_Variant
 * Method:    changeType0
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com4j_Variant_changeType0
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com4j_Variant
 * Method:    set0
 * Signature: (Ljava/lang/Object;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com4j_Variant_set0
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com4j_Variant
 * Method:    get0
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com4j_Variant_get0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com4j_Variant
 * Method:    convertTo
 * Signature: (Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com4j_Variant_convertTo
  (JNIEnv *, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
