/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com4j_tlbimp_Native */

#ifndef _Included_com4j_tlbimp_Native
#define _Included_com4j_tlbimp_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com4j_tlbimp_Native
 * Method:    readRegKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com4j_tlbimp_Native_readRegKey
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com4j_tlbimp_Native
 * Method:    enumRegKeys
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com4j_tlbimp_Native_enumRegKeys
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
