/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com4j_Win32Lock */

#ifndef _Included_com4j_Win32Lock
#define _Included_com4j_Win32Lock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com4j_Win32Lock
 * Method:    closeHandle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com4j_Win32Lock_closeHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     com4j_Win32Lock
 * Method:    createEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com4j_Win32Lock_createEvent
  (JNIEnv *, jclass);

/*
 * Class:     com4j_Win32Lock
 * Method:    activate0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com4j_Win32Lock_activate0
  (JNIEnv *, jclass, jint);

/*
 * Class:     com4j_Win32Lock
 * Method:    suspend0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com4j_Win32Lock_suspend0
  (JNIEnv *, jclass, jint);

/*
 * Class:     com4j_Win32Lock
 * Method:    suspend1
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com4j_Win32Lock_suspend1
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
