/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com4j_Native */

#ifndef _Included_com4j_Native
#define _Included_com4j_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com4j_Native
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com4j_Native_init
  (JNIEnv *, jclass);

/*
 * Class:     com4j_Native
 * Method:    createInstance
 * Signature: (Ljava/lang/String;IJJ)I
 */
JNIEXPORT jint JNICALL Java_com4j_Native_createInstance
  (JNIEnv *, jclass, jstring, jint, jlong, jlong);

/*
 * Class:     com4j_Native
 * Method:    addRef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com4j_Native_addRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     com4j_Native
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com4j_Native_release
  (JNIEnv *, jclass, jint);

/*
 * Class:     com4j_Native
 * Method:    invoke
 * Signature: (II[Ljava/lang/Object;[ILjava/lang/Class;IZI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com4j_Native_invoke
  (JNIEnv *, jclass, jint, jint, jobjectArray, jintArray, jclass, jint, jboolean, jint);

/*
 * Class:     com4j_Native
 * Method:    getErrorInfo
 * Signature: (IJJ)I
 */
JNIEXPORT jint JNICALL Java_com4j_Native_getErrorInfo
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     com4j_Native
 * Method:    getErrorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com4j_Native_getErrorMessage
  (JNIEnv *, jclass, jint);

/*
 * Class:     com4j_Native
 * Method:    queryInterface
 * Signature: (IJJ)I
 */
JNIEXPORT jint JNICALL Java_com4j_Native_queryInterface
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     com4j_Native
 * Method:    loadTypeLibrary
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com4j_Native_loadTypeLibrary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com4j_Native
 * Method:    coInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com4j_Native_coInitialize
  (JNIEnv *, jclass);

/*
 * Class:     com4j_Native
 * Method:    coUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com4j_Native_coUninitialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
